### ISSUE TITLE
how to delete a specific real server in group of servers using the module alteon_config_group_real_server

### ISSUE THREAD

**Issue by Ben-Sassi-Oussema** [Radware/radware-ansible#111]
[how to delete a specific real server in group of servers using the module alteon_config_group_real_server](https://github.com/Radware/radware-ansible/blob/master/plugins/modules/alteon_config_group_real_server.py)

**Comment by rdwrtac** [comment]
Hello Ben,

The module you mentioned is for modifying the reals setting in the group. If you need to remove real from a group, use the module alteon_config_server_group.py.

Under the server_name, remove the real server that is not needed, and run the module.
      server_names:
        - server1
        - server2  

If before you had 3 servers (called server1, server2, and server3)  after you run it you will have only 2 servers.

**Comment by Ben-Sassi-Oussema** [comment]
Thank you for your response.

I appreciate your suggestion to use alteon_config_server_group.py module for removing a real server from a group. I will explore this option and use it accordingly.

Thank you for your help.
