### ISSUE TITLE
To be able to remove directly a real server from a group server

### ISSUE THREAD

**Issue by gitnetofr** [Radware/radware-ansible#114]
**Is your feature request related to a problem? Please describe.**
We didn’t find out how to remove a real server from a group server using ansible modules.
We’ve tried with 
-	the module alteon_config_group_real_server.py – state.absent :  but it delete the group.
-	The module alteon_config_server_group.py - state absent : it returns error 
FAILED! => {"changed": false, "msg": "\nRest Request Error:\nStatus: 405\nReason: None\nurl= https://*.*.*.*:443/config/SlbNewCfgEnhGroupRealServerTable/222/221\nmethod= DELETE\nbody= None\nDetails: {\n\t\"status\": \"err\",\n\t\"message\": \"405 Method Not Allowed\",\n\t\"application message\": \"REST API unknown error\"\n}\r\n.\nAlteon"}

Radware confirmed this action is not possible with the existing modules after we've created issue 111 and asked an NFR
url issue : https://github.com/Radware/radware-ansible/issues/111

**The solution I'd like**
Thanks for developping this new functionality, in a new module if necessary

**Comment by rdwrtac** [comment]
Hello gitnetofr,

As mentioned in issue 111, if you need to remove the server from a group, use the module alteon_config_server_group.py. 
Under the server_name, remove the real server that is not needed, and run the module.
server_names:
- server1
- server2

Example:
  tasks:
  - name: alteon configuration command
    radware.radware_modules.alteon_config_server_group:
      provider: 
        server: 192.168.50.11
        user: admin
        password: admin1
        validate_certs: no
        https_port: 443
        ssh_port: 22
        timeout: 5
      state: present
      parameters:
        index: group_test123
        slb_metric: bandwidth
        health_check_id: tcp
        persist_overload_max_conn_server: enabled
        server_names:
          - server1
         - server2  
#         - server

If before you had 3 servers (called server1, server2, and server), after you run the module, you will have only 2 servers.

**Comment by gitnetofr** [comment]
Hello,
That was a workaround which looks more like a declarative mode where you have to specify the variables you want to keep and need more treatment before.
This ticket is for sure the NFR to directly remove the server I want to, as with the command 
/c/slb/group/rem

**Comment by rdwrtac** [comment]
Hello Gitnetofr,

Removing the real from the group server use the alteon_config_server_group.py, which is similar to the command /c/slb/group/rem. Just specify the group name and the servers you need in the group under the server_names parameter and no other settings are required.

  tasks:
  - name: alteon configuration command
    radware.radware_modules.alteon_config_server_group:
      provider:
        server: 192.168.50.11
        user: admin
        password: admin1
        validate_certs: no
        https_port: 443
        ssh_port: 22
        timeout: 5
      state: present
      parameters:
        index: Servers123
        server_names:
          - server6
          - server8

After running it you will have server6 and server8 in the group Servers123

**Comment by LeoBrider** [comment]
Maybe we can advice to use ansible module for alteon command string execution. It lottle breaks the declarative model , but will work

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rdwrtac** [comment]
Yes, the alteon_config_alteon_cli_command module should work as well.
