### ISSUE TITLE
There is not metric hrw in  radware.radware_modules.alteon_config_server_group

### ISSUE THREAD

**Issue by dmitryva-ticos** [Radware/radware-ansible#16]
##### CUSTOMER
Radware

##### SEVERITY
LOW
##### SUMMARY
There is not metric hrw in  radware.radware_modules.alteon_config_server_group

##### STEPS TO REPRODUCE

 - name: AddGroup
   radware.radware_modules.alteon_config_server_group:
      slb_metric: hrw

##### EXPECTED RESULTS
The task is worked without errors
##### ACTUAL RESULTS
failed: [127.0.0.1] (item={'vip': 'X.X.X.X', 'port': 80, 'service_index': 1}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "parameters": {
                "health_check_id": "tcp",
                "index": "gr_10",
                "server_names": [
                    "r1",
                    "r2"
                ],
                "slb_metric": "hrw"
            },
            "provider": {
                "https_port": 443,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "X.X.X.X",
                "ssh_port": 22,
                "timeout": 10,
                "user": "admin",
                "validate_certs": false
            },
            "revert_on_error": false,
            "state": "present",
            "write_on_change": false
        }
    },
    "item": {
        "port": 80,
        "service_index": 1,
        "vip": "X.X.X.X"
    },
    "msg": "value of slb_metric must be one of: bandwidth, hash, leastConnections, minMisses, phash, response, roundRobin, svcLeast, got: hrw found in parameters"
}

```

```

**Comment by rdwrtac** [comment]
The reported issue has identified as bug. The current ETA for fix is End of Nov.

**Comment by rdwrtac** [comment]
The issue is solved, please download the latest Ansible collection version from Ansible Galaxy and upgrade alteon-sdk python package using the command pip3 install alteon-sdk –upgrade
