### ISSUE TITLE
Getting "Error: Module unable to decode valid JSON on stdin.  Unable to figure out what parameters were passed"

### ISSUE THREAD

**Issue by irom77** [Radware/radware-ansible#19]
##### CUSTOMER
Me 

##### SEVERITY
High 

##### SUMMARY
Getting "Error: Module unable to decode valid JSON on stdin.  Unable to figure out what parameters were passed"

##### STEPS TO REPRODUCE
```
---
 tasks:
    - name: alteon real config
      radware.radware_modules.alteon_config_server:
        provider: "{{ radware_provider }}"
        # state: "{{ state }}"
        parameters:
          index: real1
          state: enabled
          ip_address: 192.168.3.1
     - name: print provider settings
       debug:
         msg: "{{ radware_provider }}" 
```

##### EXPECTED RESULTS
Get the real server created in vADC 

##### ACTUAL RESULTS
Getting "Error: Module unable to decode valid JSON on stdin.  Unable to figure out what parameters were passed"
while debug message shows correct provider settings
```
 "msg": {
        "https_port": 8443,
        "password": "xxx",
        "server": "52.17.29.13",
        "ssh_port": 22,
        "timeout": 10,
        "user": "admin",
        "validate_certs": false
    }
```

**Comment by rdwrtac** [comment]
Dear Irek Romaniuk,

Preliminary analysis suggest the error appear to be either the variable file doesn’t exist or a wrong indentation .

In a lab we did not see the aforementioned error.

Could you please let us know which Alteon version is running?

Regards,

Radware-TAC

**Comment by irom77** [comment]
Thank you for reply, I am using version 32.6.1.0 avail on Azure. My example is copy & paste of the[ one](https://github.com/Radware/radware-ansible/blob/master/examples/basic-slb/basic-slb.yaml) in repo so probably not indentation nor missing variable
![vadc](https://user-images.githubusercontent.com/1136764/102783839-8bbd5400-4369-11eb-91ce-640f6cdb16b9.JPG)

**Comment by rdwrtac** [comment]
Dear Irek Romaniuk,

Thanks for the clarification.

Further analysis we managed to recreate the error. It happens because the alteon-sdk python package isn’t installed in the Ansible server.

Please use the below command to install alteon-sdk:

"pip3 install alteon-sdk"

Regards,

Radware-TAC

**Comment by irom77** [comment]
Thank you, I've just installed alteon-sdk in virtual env of Ansible/AWX but it is still the same error. Anyways I will close the ticket as it is probably the problem on my sight

**Comment by irom77** [comment]
Quick update, I made it working, all set now . Just changed virtual env in AWX after installing alteon-sdk there. Appreciate your help
