### ISSUE TITLE
ansible module for BGP ipv4 and v6 configuration

### ISSUE THREAD

**Issue by gitnetofr** [Radware/radware-ansible#28]
##### ISSUE TYPE
 - Feature request

**Is your feature request related to a problem? Please describe.**
I need an ansible module to be able to configure BGP ipv4 and v6 parameters on Alteon OS.

**Describe the solution you'd like**
This is the configuration I need to create on alteon
```
/c/l3/
        rtrid 1.1.1.1
/c/l3/bgp/as 4567890001
/c/l3/bgp
        on
/c/l3/bgp/peer 1
        ena
        addr 1.1.1.2
        ras 4567890002
/c/l3/bgp/peer 1/redist
        default import
        vip ena
/c/l3/bgp/peer 2
        ena
        addr 2000:1:1:1:1:1:1:1
        ras 4567890002
/c/l3/bgp/peer 2/redist
        default import
        vip ena
```

**Comment by rdwrtac** [comment]
Dear gitnetofr,

The NFR has been submitted. Currently there is not ETA but you should discuss it with your Local Radware representative.

Regards,

Radware TAC
