### ISSUE TITLE
SLB port configuration

### ISSUE THREAD

**Issue by gitnetofr** [Radware/radware-ansible#31]
##### ISSUE TYPE
 - Feature request

**Is your feature request related to a problem? Please describe.**
I need an ansible module to be able to configure SLB port on Alteon OS.

**Describe the solution you'd like**
This is the configuration I need to create on alteon
```
/c/slb/port "1" 
    client dis 
    server dis 
    proxy dis 
/c/slb/port "2" 
    client ena 
    server ena 
    proxy ena 
```

**Comment by rdwrtac** [comment]
Dear gitnetofr,

The NFR has been submitted. Currently there is not ETA but you should discuss it with your Local Radware representative.

Regards,

Radware TAC
