### ISSUE TITLE
GEL configuration

### ISSUE THREAD

**Issue by gitnetofr** [Radware/radware-ansible#32]
##### ISSUE TYPE
 - Feature request

**Is your feature request related to a problem? Please describe.**
I need an ansible module to be able to configure GEL parameters like dns primary on Alteon OS.

**Describe the solution you'd like**
This is the configuration I need to create on alteon
```
/c/sys/gel
        ena
        primary "http://vdirect"
/c/sys/gel/dns
        prima 1.1.1.1
```

**Comment by rdwrtac** [comment]
Dear gitnetofr,

The NFR has been submitted. Currently there is not ETA but you should discuss it with your Local Radware representative.

Regards,

Radware TAC
