### ISSUE TITLE
enable extended_log 

### ISSUE THREAD

**Issue by rgkeg** [Radware/radware-ansible#34]
#####  ENVIRONMENT
ansible 2.10.4
python version      = 3.6.8
Software version: 31.0.15.0
Distribution: vADC 

##### SEVERITY
Low

##### SUMMARY
enable of extended_log fails 

##### STEPS TO REPRODUCE
      radware.radware_modules.alteon_config_system_logging:
        state: present
        parameters:
          extended_log_format: enabled

##### EXPECTED RESULTS
alteon : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

##### ACTUAL RESULTS
alteon: ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Alteon
[WARNING]: please verify your alteon is running a version >= ['31.0.10.0', '32.2.2.0']
fatal: [alteon]: FAILED! => {"changed": false, "msg": "\nRest Request Error:\nStatus: 405\nReason: None\nurl= https://10.1.1.1:443/config/\nmethod= PUT\nbody= {\n}\nDetails: {\n\t\"status\": \"err\",\n\t\"message\": \"405 Method Not Allowed\",\n\t\"application message\": \"REST API unknown error\"\n}\r\n.\nAlteon"}

**Comment by rdwrtac** [comment]
Dear rgkeg,

The reported issue has been identified by R&D as a bug and they are currently working on fix.

Regards,

Radware TAC

**Comment by rdwrtac** [comment]
Dear rgkeg,

I would like to update you that the fix is ready and uploaded to pypi.
Please use alteon-sdk 0.6b61, you can download it from https://pypi.org/project/alteon-sdk/


Please let me know if further clarifications needed.

Best regards,
Radware TAC
