### ISSUE TITLE
multi line -  cli_login_notice 

### ISSUE THREAD

**Issue by rgkeg** [Radware/radware-ansible#35]
Trying to configure a multi line login notice 

Example: 
----

##Company ##  ##Logo##   #######

NOTICE: This is a private network device.  .... 

----

If I do it that Way:
      radware.radware_modules.alteon_config_system_management_access:
...
          cli_login_notice: "
            ##Company ##  ##Logo##   #######
            NOTICE: This is a private network device.  ....
            "

result: 
 /cfg/sys/notice noprompt
         ##Company ##  ##Logo##   ####### NOTICE: This is a private network device.  ....  

If I use a "|" (https://adminswerk.de/multi-line-string-yaml-ansible-I/) 
I get - 405 Method Not Allowed  

Also I tried using a "banner.txt" did also run into the same Problem. 

Can you please provide a solution/example  for a multi line Login notice  with line break

**Comment by rdwrtac** [comment]
Dear rgkeg,

I would like to update you that this is being analyzed by our R&D team.

I will keep you posted with any new information.

**Comment by rdwrtac** [comment]
Dear rgkeg,

After looking into this case, when configuring multi line notice you need to put last line with only a '.' sign.

Should be like the example below:

"
##Company ## ##Logo## #######        
 NOTICE This is a private network device. ....
.
"

Please let me know if this is helpful.

Best regards,
Radware TAC

**Comment by rgkeg** [comment]
Hello Radware TAC 

I tried it a couple times. 

Part of the Script:
              cli_login_notice:
                "
                ##Company ## ##Logo## #######
                NOTICE This is a private network device. ....
                .
                "
          delegate_to: localhost

The result is : 

=> Pending configuration
 /cfg/sys/notice noprompt
         ##Company ## ##Logo## ####### NOTICE This is a private network device. .... . 
<= Current configuration
 /cfg/sys/notice noprompt
.....
 /c/sys/access/mgmt/add 1.1.1.1  255.255.255.255 ssh|https|snmp|report
 /c/sys/access/mgmt/add 2.2.2.2 255.255.255.255 ssh|https|snmp
...

As you see it is still a single line. Even worst is that he kills my mgmt access list 

Thanks
Robert

**Comment by rdwrtac** [comment]
Hi Robert,

Please try the following:

cli_login_notice:
"
##Company ## ##Logo## #######\\n
NOTICE This is a private network device. \\n
.
"

Thank you,
Radware TAC

**Comment by rgkeg** [comment]
Hello Tac

No it doesn't work.  I tried

              cli_login_notice:
                "
                ##Company ## ##Logo## ####### \n
                NOTICE This is a private network device. \n
                .
                "

The Result is then:

url= https://10.x.x.x1:443/config/
method= PUT
body= {
"agNewCfgLoginNotice":" ##Company ## ##Logo## #######
 NOTICE This is a private network device.
 . ",
}
Details: {
        "status": "err",
        "message": "405 Method Not Allowed",
        "application message": "REST API unknown error"

It is possible to open an regular Radware TAC Case ?

Thanks
Robert

Mit freundlichen Grüßen / Kind regards

Robert Kegerreis

Dipl.-Ing. (FH)
Senior Datacenter Architect - Loadbalancer & DCLAN
Datacenter Network Aviation Industry Services
                                                                                                                
                                                                                                                
                                                                                                                
                                                                                                                
                                                                                                                
 Phone:            +49-151 589 20669                    IBM Deutschland Aviation Industry                       
                                                       Services GmbH                                            
                                                                                                                
 Email:            ***@***.***                 Am Weiher 24                                            
                                                                                                                
                                                        65817 Kelsterbach                                       
                                                                                                                
                                                                                                                
                                                                                                                
 IBM Data Privacy                                                                                               
 Statement                                                                                                      
                                                                                                                
 IBM Deutschland                                                                                                
 Aviation Industry                                                                                              
 Services GmbH /                                                                                                
 Geschäftsführung:                                                                                              
 Thomas Rittirsch,                                                                                              
 Dr. Thomas Wolter                                                                                              
 Sitz der                                                                                                       
 Gesellschaft:                                                                                                  
 Kelsterbach                                                                                                    
 Registergericht:                                                                                               
 Amtsgericht                                                                                                    
 Darmstadt, HRB                                                                                                 
 94232                                                                                                          
                                                                                                                






From:	rdwrtac ***@***.***>
To:	Radware/radware-ansible ***@***.***>
Cc:	rgkeg ***@***.***>, Author
            ***@***.***>
Date:	04.05.2021 10:51
Subject:	[EXTERNAL] Re: [Radware/radware-ansible] multi line -
            cli_login_notice  (#35)



Hi Robert, Please try the following: cli_login_notice: " ##Company ##
##Logo## #######\n NOTICE This is a private network device. \n . " Thank
you, Radware TAC — You are receiving this because you authored the thread.
‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍‍ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd


Hi Robert,


Please try the following:


cli_login_notice:
"
##Company ## ##Logo## #######\n
NOTICE This is a private network device. \n
.
"


Thank you,
Radware TAC


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rdwrtac** [comment]
Hi Robert,

Please try to use "\\n<file://n>" and not "\n"
Every time the string is processed (sprint) then "\\" turns to "\"

Please let me know if this is woking

Thank you,
Radware TAC

**Comment by rdwrtac** [comment]
Hello rgkeg,

Sorry for the late response. The issue was reported as a bug and fixed on Alteon version 32.4.7.0.
Please upgrade Alteon to the fixed version.

Best regards,
Radware TAC
