### ISSUE TITLE
syslog ipv6 module - alteon_config_system_logging doesn't replace ipv6 to ipv4

### ISSUE THREAD

**Issue by chensagi** [Radware/radware-ansible#38]
##### SEVERITY

Low

##### SUMMARY

when configuring syslog to be an ipv6 and then ipv4, the ipv4 configuration isn't applied

##### STEPS TO REPRODUCE

configure ipv4 syslog address -
syslog_servers:
  host1:
    ip4_address: 10.10.10.4
    port: 514
    severity: info6
    facility: local3
    module: all

configure ipv6 syslog address -
syslog_servers:
  host1:
    ip6_address: fd25:9178:faec:54ab::1
    port: 514
    severity: info6
    facility: local3
    module: all

##### EXPECTED RESULTS

ipv6 configured on alteon host1

##### ACTUAL RESULTS

ipv4 still configured on alteon host1

```

```

**Comment by rdwrtac** [comment]
Dear chensagi,

In order to further analyze, please provide with the following information:

1. Example of the playbook used.
2. What software version is running on the Alteon?

Thank you,
Radware TAC
