### ISSUE TITLE
Hname in virt service

### ISSUE THREAD

**Issue by GeoffreyRioux** [Radware/radware-ansible#56]
Hello,

I wanted to know if you can add possibility to define hname in service virt module ansible radware for alteon : radware.radware_modules.alteon_config_virtual_service

Thanks

Regards

**Comment by rdwrtac** [comment]
Hello GeoffreyRioux,

I would appreciate it if you could share more details about which hname you are referring to because it is not clear which one?
Maybe you are referring to Hostname under the Virtual Services >>> Properties?

 Best regards,

**Comment by GeoffreyRioux** [comment]
Hello,

I am opening this ticket again. I am talking about hname like this : 

/c/slb/virt/service 80/hname

Which is seems to be not available for the moment with the collection.

May you have more information about that

Best regards
