### ISSUE TITLE
attributes description duplicated for backup_type and vip_health_check_mode

### ISSUE THREAD

**Issue by brxdeop** [Radware/radware-ansible#67]
Not sure which is the right description for which attribute. 
Could you please have a look and modify if necessary.
 
https://github.com/Radware/radware-ansible/blob/33d6da16acf1bf9f58944bab14c53d1a1fa7b7ef/plugins/modules/alteon_config_server_group.py#L153-L178

**Comment by rdwrtac** [comment]
Hello brxdeop,

Thank you for pointing it out. It looks like the 'backup_type' description was duplicated to the 'vip_health_check_mode'.
As the attribute, 'vip_health_check_mode' should have one of the following values enabled/disabled.

I'm currently validating this with R&D, and I will update you accordingly.

Best regards,
