### ISSUE TITLE
snmpv3_usm_user - missing "name"  

### ISSUE THREAD

**Issue by rgkeg** [Radware/radware-ansible#68]
##### SUMMARY
Creating new SNMP V3 User and the needed Name is not there 

##### STEPS TO REPRODUCE
Script Example 
          state: present
          parameters:
            usm_user_name: UserTEST2
            authentication_protocol: SHA
            authentication_password: authtestpw
            privacy_protocol: AES128
            privacy_password: privtestpw

##### EXPECTED RESULTS
 /c/sys/ssnmp/snmpv3/usm 4
        name "Usertest"
        auth sha
        authpw ...
        priv aes128
        privpw ...

##### ACTUAL RESULTS
 /c/sys/ssnmp/snmpv3/usm 4
        auth sha
        authpw ....
        priv aes128
        privpw ...

Tried it a couple time. vADC is running on 32.4.8.50

**Comment by rgkeg** [comment]
Looks that it this is fixed with 32.4.9.0. Correct ?

**Comment by rdwrtac** [comment]
Hello rgkeg,

Versions 32.4.9.0 and the newer versions I tested include the fix with the name. I tried version 32.4.8.50, and it does not have this fix with the name.

Best regards,
Dmitri
