### ISSUE TITLE
request to implement READ_ALL action for slb modules

### ISSUE THREAD

**Issue by brxdeop** [Radware/radware-ansible#76]
Hello guys,

to push forward the capabilities of this ansible module i open this request to add the capability of reading any table content which normally is implemented as action READ_ALL in SDK.

**The context**

Using alteon devices in a multi tenancy context requires prefixing resource's indices with a giving string. This in order to be able to retrieve a tenant configuration all over the alteon resources ( mainly SLB level resource ). 

*N.B.* a resource : an element of any configurable entity like {server, health_check_http, health_check_tcp, virtual_service, virtual_server, ... } 

For the moment the alteon-sdk implement reading the content of a given table (resource entity).
we can for example retrieve all the real servers and by applying regex we will get real servers for a given tenant.
this is not implemented yet in this ansible module. we only read the configuration of single resource by giving its exact index.

**Expected Feature**
implementing the READ_ALL that allow to retrieve the content of table (configurable entity)
Even better implement the possibility to use Regex at module level.

**Current alternative**
For these needs avoid using ansible, instead using Python SDK

**Comment by rdwrtac** [comment]
Hello brxdeop,

I would appreciate it if you could clarify what is the request, because I didn't quite understood it based on the content.

**Comment by brxdeop** [comment]
Hello @rdwrtac 
In another way, the request is to implement **read_all** not only **read** in ansible modules.
**read**  : allows us to retrieve information if we already know the resource index.
**read_all** : allow to retrieve all the table content (not mandatory to know the exact index)
More with further regex or result handling we can perform filtering on retrieved data.

**Comment by rdwrtac** [comment]
Hello brxdeop,

I checked regarding your request.
There is a module called "alteon_device_facts". In this module, you can use the parameter "all" that will retrieve all Alteon parameters without the need to know the specific content.

**Comment by rdwrtac** [comment]
Hello brxdeop,

R&D noticed that you said that you can do it via alteon-SDK but not via ansible.
They didn’t understand this statement, and they would appreciate it if you could share how it was done through the SDK without ansible?

**Comment by brxdeop** [comment]
I want to also to add that constructors inherite from `AlteonConfigurator` which iherite from `DeviceConfigurator`, This last one has a **read_all** method which mean we can basically do exactly the same with contructors also.

To get for example real servers we have the possibility to.

```python
realservers = client.api.conf.type.server.read_all()
```

**Comment by rdwrtac** [comment]
Thank you brxdeop, for the explanation and examples regarding the SDK.

I will discuss it with R&D, and I will update you.

**Comment by rdwrtac** [comment]
Hello brxdeop,

R&D said that you can run device facts only on a specific module and you don’t have to gather “all” parameters.
The way to do it is to write specifically the module name in the yaml file that runs gathering facts instead of writing “all”
For example use “– server” instead of “– all”
You can find the choices for running in alteon_device_facts

**Comment by brxdeop** [comment]
Thank you !
I will try this and feed you back.

**Comment by brxdeop** [comment]
Hello back,
I tested the `alteon_device_facts` module. it implements what i expected.
I just want to mention that the documentation has mistakes regarding the module itself and it should be corrected.

https://github.com/Radware/radware-ansible/blob/1afea346accf7a453dcd6c192da16b98ef7df53d/plugins/modules/alteon_device_facts.py#L236

should be replaced by.

`radware.radware_modules.alteon_device_facts:`

**Comment by rdwrtac** [comment]
Hello brxdeop,

R&D informed the documentation on the module will be fixed with Alteon version 33.5.1.0 which should be released at the end of June.
