### ISSUE TITLE
Recommendattion for securing access to alteons while using radware-ansible

### ISSUE THREAD

**Issue by brxdeop** [Radware/radware-ansible#79]
Hello,

This is not a really feature request but a recommendation request.

The context

I am using multiple alteon devices in a multi tenancy context. And an ansible node where the playbooks are run over the multiples devices. the structure used to connect to alteons (radware_provider) in your inventories mentions the user/password as attributes in clear which is to avoid.

The recommendation request.
What are your recommendations regarding.
- secure user/password in transit between ansible node and alteon devices,
- secure user/password at rest on Ansible node (kind of ansible-vault),

Could you provide also more information about.
- radware_provider `validate_certs` attribute,
- radware_provider `ssh_port` attribute (the use is not actually mandatory but if specified can we privilege rsa-keys as no related attribute is there ),

 Thank you.

**Comment by rdwrtac** [comment]
Hello brxdeop,

For the top part, I will need to check these subjects.
As for attributes:
validate_certs:
        description:
          - If C(no), SSL certificates will not be validated.
          - This should only set to C(no) used on personally controlled sites using self-signed certificates.
        required: true
        default: null
        type: bool

 ssh_port:
      description:
        - Radware Alteon ssh port.

**Comment by rdwrtac** [comment]
Hello brxdeop,

From testing in my lab when executing playbook, the user/password is not clear in communication transit between ansible node and Alteon device.
As for secure user/password this need to be done from the Ansible node to encrypt them with a script, and not directly from the Alteon provider.
