### ISSUE TITLE
Assign virt to Service group when ha service mode is used

### ISSUE THREAD

**Issue by gitnetofr** [Radware/radware-ansible#8]
**Is your feature request related to a problem? Please describe.**
When HA service mode is used, we have to configure service groups and affect floating ips, virt,ha ports, to it in order to have VIPs reachable.
This is not configurable with the existing modules

**Describe the solution you'd like**
I want to be able to create this kind of configuration :
```
/c/l3/ha/service 1
        ena
        failback always
        pref active
        def 1 2
        addfip 1
        addvip 1
/c/l3/ha/service 1/trigger/gwtrck
        ena
        add 1
        add 2
/c/l3/ha/service 1/trigg
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Nofarliv** [comment]
Hi,

The ticket is in work.
We will provide ETA once we'll finish analysis.

Thanks,
Nofar
