### ISSUE TITLE
Name parameters missing in alteon_config_server and alteon_config_server_group modules

### ISSUE THREAD

**Issue by gitnetofr** [Radware/radware-ansible#9]
##### SUMMARY
There is no parameters in config_server and alteon_config_server_group modules to be able to configure names on real servers and group servers

##### STEPS TO REPRODUCE
````
- name: Create a real server
  alteon_config_server:
````
and
````
- name: Create a group of servers
  alteon_config_server_group:
````
##### EXPECTED RESULTS
````
/c/slb/real x/ name "****"
/c/slb/group y/ name "****"

````

##### ACTUAL RESULTS

```

```

**Comment by Nofarliv** [comment]
Hi,

The ticket is in work.
We will provide ETA once we'll finish analysis.

Thanks,
Nofar
